!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  antiwindup: true
  d: 100.0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      antiwindup: true
      d: 100.0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      i: 10.0
      i_clamp_max: 100.0
      i_clamp_min: -100.0
      id: 0
      name: Default
      p: 1500.0
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
    state: []
  i: 10.0
  i_clamp_max: 100.0
  i_clamp_min: -100.0
  p: 1500.0
state: []
