// Generated by gencpp from file commissioning_robot/PhaseReport.msg
// DO NOT EDIT!


#ifndef COMMISSIONING_ROBOT_MESSAGE_PHASEREPORT_H
#define COMMISSIONING_ROBOT_MESSAGE_PHASEREPORT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace commissioning_robot
{
template <class ContainerAllocator>
struct PhaseReport_
{
  typedef PhaseReport_<ContainerAllocator> Type;

  PhaseReport_()
    : phase(0)
    , description()  {
    }
  PhaseReport_(const ContainerAllocator& _alloc)
    : phase(0)
    , description(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _phase_type;
  _phase_type phase;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _description_type;
  _description_type description;





  typedef boost::shared_ptr< ::commissioning_robot::PhaseReport_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::commissioning_robot::PhaseReport_<ContainerAllocator> const> ConstPtr;

}; // struct PhaseReport_

typedef ::commissioning_robot::PhaseReport_<std::allocator<void> > PhaseReport;

typedef boost::shared_ptr< ::commissioning_robot::PhaseReport > PhaseReportPtr;
typedef boost::shared_ptr< ::commissioning_robot::PhaseReport const> PhaseReportConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::commissioning_robot::PhaseReport_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::commissioning_robot::PhaseReport_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::commissioning_robot::PhaseReport_<ContainerAllocator1> & lhs, const ::commissioning_robot::PhaseReport_<ContainerAllocator2> & rhs)
{
  return lhs.phase == rhs.phase &&
    lhs.description == rhs.description;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::commissioning_robot::PhaseReport_<ContainerAllocator1> & lhs, const ::commissioning_robot::PhaseReport_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace commissioning_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::commissioning_robot::PhaseReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::commissioning_robot::PhaseReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::commissioning_robot::PhaseReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::commissioning_robot::PhaseReport_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commissioning_robot::PhaseReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::commissioning_robot::PhaseReport_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::commissioning_robot::PhaseReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73ce18b297c87cc885b69b7c94ec8474";
  }

  static const char* value(const ::commissioning_robot::PhaseReport_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73ce18b297c87cc8ULL;
  static const uint64_t static_value2 = 0x85b69b7c94ec8474ULL;
};

template<class ContainerAllocator>
struct DataType< ::commissioning_robot::PhaseReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "commissioning_robot/PhaseReport";
  }

  static const char* value(const ::commissioning_robot::PhaseReport_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::commissioning_robot::PhaseReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 phase\n"
"string description\n"
;
  }

  static const char* value(const ::commissioning_robot::PhaseReport_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::commissioning_robot::PhaseReport_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.phase);
      stream.next(m.description);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PhaseReport_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::commissioning_robot::PhaseReport_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::commissioning_robot::PhaseReport_<ContainerAllocator>& v)
  {
    s << indent << "phase: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.phase);
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.description);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMISSIONING_ROBOT_MESSAGE_PHASEREPORT_H
